### ISSUE TITLE
Why are you making this instead of just using PRINT_PREREQ on command-line of Makefile.PL?

### ISSUE THREAD

**Issue by mohawk2** [perlancar/perl-ExtUtils-MakeMaker-Dump#1]

**Comment by perlancar** [comment]
Ah, I didn't know about PREREQ_PRINT/PRINT_PREREQ. Thanks for the information.

But I also need distribution name and abstract, and the other prereqs (CONFIGURE_REQUIRES, et al) and potentially other stuffs too. I didn't see an option to print everything?

**Comment by perlancar** [comment]
BTW, FYI, I'm using this module for App::lcpan, which indexes a local CPAN mirror by extracting distribution information from Makefile.PL or Build.PL (if the release files don't have META.json or META.yml).

**Comment by mohawk2** [comment]
You know you can just read the distro's META.json/yml, right?

**Comment by mohawk2** [comment]
By the way, why not join IRC and chat on #toolchain on irc.perl.org?

**Comment by mohawk2** [comment]
You can use this URL to do it super-easily, and the folks there would love to work with you since you clearly have lots of energy and ideas:

http://client00.chat.mibbit.com/?server=irc.perl.org&channel=%23toolchain&nick=perlancar

**Comment by perlancar** [comment]
I'm not much of an IRC guy, but I've just joined the channel.

**Comment by perlancar** [comment]
OK, so after discussion I've added this item on my todo list for this dist:

```
** TODO [2015-01-14 Wed] lcpan: use 'perl Makefile.PL/Build.PL' and get info from the generated MYMETA.* instead of monkey-patching
- this has the benefit of not requiring extra modules
- after that: "delete EUMM::Dump and MB::Dump"
```

also:

```
** TODO [2015-01-14 Wed] lcpan: when executing 'perl Makefile.PL', make sure we set non-interactive mode
:    dolmenperlancar, at least you should ensure that $ENV{NON_INTERACTIVE}=1 and STDIN is closed (or not directed to a terminal) to avoid interactive questions
:    dolmen... from Makefile.PL
:    perlancarso far i use the alarm() trick
:    perlancarbut that's not the correct way, i know
:    dolmenthere is just no correct way: install tools were just not designed for that
:    dolmenthis is why MYMETA has been invented
:    haargPERL_MM_USE_DEFAULT=1
```

**Comment by mohawk2** [comment]
Nice work! I look forward to working with you further.
